import UIKit

/// Harness activity center with explicit state groups. Rows are projections of
/// Runtime only; an unavailable server capability remains absent rather than
/// being replaced with demo content.
final class HarnessActivityCenterViewController: UIViewController, UITableViewDataSource, UITableViewDelegate {
    private let runtime: HarnessRuntime
    private let table = UITableView(frame: .zero, style: .insetGrouped)
    private var groups: [(String, [(String, String, String, UIColor, () -> Void)])] = []
    init(runtime: HarnessRuntime) { self.runtime = runtime; super.init(nibName: nil, bundle: nil); title = "活动中心" }
    @available(*, unavailable) required init?(coder: NSCoder) { fatalError() }
    override func viewDidLoad() { super.viewDidLoad(); view.backgroundColor = DHTheme.background; navigationItem.rightBarButtonItem = UIBarButtonItem(barButtonSystemItem: .close, target: self, action: #selector(close)); table.backgroundColor = .clear; table.dataSource = self; table.delegate = self; table.register(ActivityCell.self, forCellReuseIdentifier: "activity"); table.translatesAutoresizingMaskIntoConstraints = false; view.addSubview(table); NSLayoutConstraint.activate([table.leadingAnchor.constraint(equalTo: view.leadingAnchor), table.trailingAnchor.constraint(equalTo: view.trailingAnchor), table.topAnchor.constraint(equalTo: view.safeAreaLayoutGuide.topAnchor), table.bottomAnchor.constraint(equalTo: view.bottomAnchor)]); reload(); runtime.onNavigationChange = { [weak self] in DispatchQueue.main.async { self?.reload() } } }
    @objc private func close() { dismiss(animated: true) }
    @objc private func reload() { var pending: [(String, String, String, UIColor, () -> Void)] = []; runtime.pendingApprovals.forEach { request in pending.append((request.isHighRisk ? "高风险审批" : "审批待处理", request.toolName + (request.target.map { " · \($0)" } ?? ""), request.isHighRisk ? "exclamationmark.triangle.fill" : "checkmark.shield", request.isHighRisk ? DHTheme.danger : DHTheme.warning, { [weak self] in self?.showApproval(request) })) }; runtime.pendingQuestions.forEach { question in pending.append(("Agent 等待回答", question.questions.first?.question ?? "需要你的选择", "questionmark.bubble.fill", DHTheme.accent, { [weak self] in self?.showQuestion(question) })) }; var running: [(String, String, String, UIColor, () -> Void)] = []; runtime.sessions.filter { $0.running }.forEach { session in running.append(("正在运行", session.title, "bolt.fill", DHTheme.accent, { [weak self] in self?.runtime.openSession(session.id); self?.dismiss(animated: true) })) }; groups = []; if !pending.isEmpty { groups.append(("需要处理", pending)) }; if !running.isEmpty { groups.append(("正在运行", running)) }; if groups.isEmpty { groups = [("最近完成", [("暂无待处理活动", "连接到 Harness 后，真实审批、问题和运行状态会出现在这里。", "checkmark.circle", DHTheme.success, {})])] }; table.reloadData() }
    private func showApproval(_ request: HarnessApprovalRequest) { present(UINavigationController(rootViewController: HarnessApprovalViewController(runtime: runtime, request: request)), animated: true) }
    private func showQuestion(_ pending: HarnessPendingQuestion) { let c = QuestionViewController(pending: pending, onAnswer: { [weak self] answers in self?.runtime.answerQuestion(pending, answers: answers); self?.dismiss(animated: true) }, onCancel: { [weak self] in self?.runtime.cancelQuestion(pending); self?.dismiss(animated: true) }); present(UINavigationController(rootViewController: c), animated: true) }
    func numberOfSections(in tableView: UITableView) -> Int { groups.count }
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int { groups[section].1.count }
    func tableView(_ tableView: UITableView, titleForHeaderInSection section: Int) -> String? { groups[section].0 }
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell { let cell = tableView.dequeueReusableCell(withIdentifier: "activity", for: indexPath) as! ActivityCell; let row = groups[indexPath.section].1[indexPath.row]; cell.configure(title: row.0, detail: row.1, icon: row.2, color: row.3); return cell }
    func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) { groups[indexPath.section].1[indexPath.row].4(); tableView.deselectRow(at: indexPath, animated: true) }
}

private final class ActivityCell: UITableViewCell {
    private let icon = UIImageView(); private let titleLabel = UILabel(); private let detailLabel = UILabel()
    override init(style: UITableViewCell.CellStyle, reuseIdentifier: String?) { super.init(style: style, reuseIdentifier: reuseIdentifier); backgroundColor = DHTheme.surface; icon.contentMode = .scaleAspectFit; icon.widthAnchor.constraint(equalToConstant: 28).isActive = true; let labels = UIStackView(arrangedSubviews: [titleLabel, detailLabel]); labels.axis = .vertical; labels.spacing = 3; titleLabel.font = DHTheme.font(.body, weight: .semibold); titleLabel.textColor = DHTheme.text; detailLabel.font = DHTheme.font(.caption1); detailLabel.textColor = DHTheme.secondaryText; detailLabel.numberOfLines = 2; let arrow = UIImageView(image: UIImage(systemName: "chevron.right")); arrow.tintColor = DHTheme.tertiaryText; let row = UIStackView(arrangedSubviews: [icon, labels, arrow]); row.axis = .horizontal; row.spacing = 12; row.alignment = .center; row.translatesAutoresizingMaskIntoConstraints = false; contentView.addSubview(row); NSLayoutConstraint.activate([row.leadingAnchor.constraint(equalTo: contentView.leadingAnchor, constant: 16), row.trailingAnchor.constraint(equalTo: contentView.trailingAnchor, constant: -16), row.topAnchor.constraint(equalTo: contentView.topAnchor, constant: 13), row.bottomAnchor.constraint(equalTo: contentView.bottomAnchor, constant: -13)]) }
    @available(*, unavailable) required init?(coder: NSCoder) { fatalError() }
    func configure(title: String, detail: String, icon: String, color: UIColor) { titleLabel.text = title; detailLabel.text = detail; self.icon.image = UIImage(systemName: icon); self.icon.tintColor = color; accessibilityLabel = "\(title)，\(detail)" }
}

/// Full-screen is reserved for high-risk requests; ordinary approvals stay a
/// sheet. The labels describe the risk independently of the colors.
final class HarnessApprovalViewController: UIViewController {
    private let runtime: HarnessRuntime; private let request: HarnessApprovalRequest
    init(runtime: HarnessRuntime, request: HarnessApprovalRequest) { self.runtime = runtime; self.request = request; super.init(nibName: nil, bundle: nil); title = "审批"; modalPresentationStyle = request.isHighRisk ? .fullScreen : .pageSheet }
    @available(*, unavailable) required init?(coder: NSCoder) { fatalError() }
    override func viewDidLoad() { super.viewDidLoad(); view.backgroundColor = DHTheme.background; navigationItem.leftBarButtonItem = UIBarButtonItem(barButtonSystemItem: .close, target: self, action: #selector(close)); let scroll = UIScrollView(); scroll.translatesAutoresizingMaskIntoConstraints = false; let stack = UIStackView(); stack.axis = .vertical; stack.spacing = 14; stack.translatesAutoresizingMaskIntoConstraints = false; view.addSubview(scroll); scroll.addSubview(stack); NSLayoutConstraint.activate([scroll.leadingAnchor.constraint(equalTo: view.leadingAnchor), scroll.trailingAnchor.constraint(equalTo: view.trailingAnchor), scroll.topAnchor.constraint(equalTo: view.safeAreaLayoutGuide.topAnchor), scroll.bottomAnchor.constraint(equalTo: view.bottomAnchor), stack.leadingAnchor.constraint(equalTo: scroll.contentLayoutGuide.leadingAnchor, constant: 18), stack.trailingAnchor.constraint(equalTo: scroll.contentLayoutGuide.trailingAnchor, constant: -18), stack.topAnchor.constraint(equalTo: scroll.contentLayoutGuide.topAnchor, constant: 22), stack.bottomAnchor.constraint(equalTo: scroll.contentLayoutGuide.bottomAnchor, constant: -24), stack.widthAnchor.constraint(equalTo: scroll.frameLayoutGuide.widthAnchor, constant: -36)]); let risk = UILabel(); risk.text = "\(request.isHighRisk ? "高风险" : "需要批准") · \(request.toolName)"; risk.font = DHTheme.font(.title2, weight: .bold); risk.textColor = request.isHighRisk ? DHTheme.danger : DHTheme.warning; risk.numberOfLines = 0; stack.addArrangedSubview(risk); stack.addArrangedSubview(info("Agent 想做什么", request.reason ?? "服务端请求执行此工具。")); if let target = request.target { stack.addArrangedSubview(info("作用对象", target)) }; if let detail = request.detail { stack.addArrangedSubview(code(detail)) }; if let args = request.arguments { stack.addArrangedSubview(code(args)) }; let note = UILabel(); note.text = "风险由工具名、对象和请求内容共同表达，不只依赖颜色。批准结果会回写 Harness 事件。"; note.font = DHTheme.font(.subheadline); note.textColor = DHTheme.secondaryText; note.numberOfLines = 0; stack.addArrangedSubview(note); let actions = UIStackView(); actions.axis = .horizontal; actions.spacing = 10; let deny = dhButton(title: "拒绝", systemName: "xmark", filled: false) { [weak self] in self?.answer("denied") }; let allow = dhButton(title: "仅允许一次", systemName: "checkmark", filled: true) { [weak self] in self?.answer("allowed-once") }; actions.addArrangedSubview(deny); actions.addArrangedSubview(allow); stack.addArrangedSubview(actions) }
    private func info(_ title: String, _ text: String) -> UIView { let stack = UIStackView(); stack.axis = .vertical; stack.spacing = 5; let t = UILabel(); t.text = title; t.font = DHTheme.font(.caption1, weight: .semibold); t.textColor = DHTheme.secondaryText; let b = UILabel(); b.text = text; b.font = DHTheme.font(.body); b.textColor = DHTheme.text; b.numberOfLines = 0; stack.addArrangedSubview(t); stack.addArrangedSubview(b); return stack }
    private func code(_ text: String) -> UIView { let label = UILabel(); label.text = text; label.font = UIFont.monospacedSystemFont(ofSize: 14, weight: .regular); label.textColor = DHTheme.text; label.numberOfLines = 0; let card = UIView(); card.dhApplyCard(backgroundColor: DHTheme.processSurface, cornerRadius: 12, borderColor: DHTheme.separator.withAlphaComponent(0.3)); label.translatesAutoresizingMaskIntoConstraints = false; card.addSubview(label); NSLayoutConstraint.activate([label.leadingAnchor.constraint(equalTo: card.leadingAnchor, constant: 12), label.trailingAnchor.constraint(equalTo: card.trailingAnchor, constant: -12), label.topAnchor.constraint(equalTo: card.topAnchor, constant: 12), label.bottomAnchor.constraint(equalTo: card.bottomAnchor, constant: -12)]); return card }
    private func answer(_ decision: String) { runtime.answerApproval(clientID: request.clientID, eventID: request.eventID, decision: decision); dismiss(animated: true) }
    @objc private func close() { dismiss(animated: true) }
}
